###
PUT http://localhost:5000/v1/traveler/67138a600801669c166b8301
Content-Type: application/json

{
  "phone_number": "gg1@gmail.com",
  "currency": "gg1@gmail.com",
  "name": "gg1@gmail.com",
  "surname": "gg1@gmail.com",
  "birth_date": "1998-05-10T00:00Z",
  "interested_in": [2],
  "user_id": "6713b798fe58e0c5188d2569"
}

<> 2024-10-19T183138.404.json

