###
GET http://localhost:5000/v1/itinerary/completed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDA2ODg5NywianRpIjoiYThkNzA3MmYtODQ1My00ZGFiLWIxNzctMGYxMWVkNWY2ZjA0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MTM4YTYwMDgwMTY2OWMxNjZiODMwMSIsIm5iZiI6MTczMDA2ODg5NywiY3NyZiI6ImE0ZGEwYThlLTM3YjQtNDExMy1iNDNmLTdjMWRlZjgyZDIxNCIsImV4cCI6MTczMDA2OTc5Nywicm9sZXMiOlsiVFJBVkVMRVIiXSwiZW1haWwiOiJnaXVzZXBwZS5pYXZhcm9uZTE5QGdtYWlsLmNvbSJ9.-nfSDhiXMU0p53u1dPkodBtJENjymCZXQDfD99_ZLAk

<> 2024-10-28T013306.422.json
<> 2024-10-27T234419.200.json
<> 2024-10-27T234308.500.json