###
POST http://localhost:5000/v1/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyODg0NDIxOSwianRpIjoiODM5Mzg5YTQtOGUyYy00NjQ3LWI3ZWUtNDZjZTlkNjQ5OGJkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY3MGJmNmUwYjIwOTNkODM0NTc0MzRkYiIsIm5iZiI6MTcyODg0NDIxOSwiY3NyZiI6ImY0YTJmZDU3LTg2ODAtNDdiMy1hNjZkLTRlN2FlZWU4MTJiOSIsImV4cCI6MTcyODg0NTExOSwicm9sZXMiOlsiVFJBVkVMRVIiXSwiZW1haWwiOiJnaXVzZXBwZS5pYXZhcm9uZTE5QGdtYWlsLmNvbSJ9.5UjWQp7pPYyVxgu6mU-EF2qS1gSD76PhHCa_sEQjhi8
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyODg0NDIxOSwianRpIjoiNjcwNjkyY2EtODg3Yi00MTBjLTg1MGMtODE3MzlmMGZkMDMyIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiI2NzBiZjZlMGIyMDkzZDgzNDU3NDM0ZGIiLCJuYmYiOjE3Mjg4NDQyMTksImNzcmYiOiIyOTdlNGE2My0wYmI2LTRkMGItOWNlNy00ZGI3NzMzMzYyMWMiLCJleHAiOjE3MzE0MzYyMTksInJvbGVzIjpbIlRSQVZFTEVSIl0sImVtYWlsIjoiZ2l1c2VwcGUuaWF2YXJvbmUxOUBnbWFpbC5jb20ifQ.XBIF_W4XsNMaGJaw-d7pENyuVqtpGpFPzY-Hh26Z7so"
}
