###
POST http://localhost:5000/v1/user/refresh-token
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyODg0MTYyNSwianRpIjoiZjIzMDIwNWItY2U2ZS00OTQ3LThkYzItZWQxMjE4ZGNlYWUwIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiI2NzBiZjZlMGIyMDkzZDgzNDU3NDM0ZGIiLCJuYmYiOjE3Mjg4NDE2MjUsImNzcmYiOiJlYmU1MTAyOC05ZTEwLTRkYmQtYWM0ZC04ZWYzZTAzODU0NDgiLCJleHAiOjE3MzE0MzM2MjUsInJvbGVzIjpbIlRSQVZFTEVSIl0sImVtYWlsIjoiZ2l1c2VwcGUuaWF2YXJvbmUxOUBnbWFpbC5jb20ifQ.5FP4L_0MdaRjGhotpaziaS8_jaH7jrt9I2kgMQERywM"
}
